FROM haproxytech/haproxy-alpine:2.6

ADD ./docker/haproxy/lua /usr/local/etc/haproxy/lua
ADD ./docker/haproxy/tunnels.map /usr/local/etc/haproxy/
ADD ./docker/haproxy/errors/* /usr/local/etc/haproxy/errors/
